### ISSUE TITLE
BDOS doesn't test for disk full when allocating blocks

### ISSUE THREAD

**Issue by ivop** [davidgiven/cpm65#170]
I stumbled upon this error with a new program I'm writing, and can reproduce it with copy:

![bbc-crash](https://github.com/user-attachments/assets/38d96a11-c9cd-40d4-8276-a00b51ec65ed)

All other ports seem to work correctly when all of bss is used and the program calls cpm_warmboot() after that.

Edit: looks like this has nothing to do with bss being fully used, but running out of disk space. I suppose this shouldn't happen though?

**Comment by davidgiven** [comment]
This sounds like the DPH is misconfigured and set up for a bigger disk than MOS actually has. MOS then tries to expand the disk file, fails, and throws an error. MOS errors all use quasi-exception handling via brk and there is no brk handler to catch them, which is why it prints the message and crashes. Both of these things need fixing.

**Comment by davidgiven** [comment]
I've encountered a similar problem elsewhere; turns out the BDOS doesn't check for disk full conditions when allocating new blocks and will just run off the end of the bitmap. Oops!
